---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age136ladmslrftxhmkctamq7kpmpfdaqhz4m4pqqkz4vjdc5cpgeqmq27vk7j"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age136ladmslrftxhmkctamq7kpmpfdaqhz4m4pqqkz4vjdc5cpgeqmq27vk7j"
stores:
  yaml:
    indent: 2
