# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3Tkij/5AiFIDKINQDAZ8DlhZJsMoMyFpmpublV/u+ktVqpLUGRQWcQ==,iv:05KQDVQFht+3VZqoDt4B1OQK8WT3QFwfmYRjxpscd1M=,tag:7aQmSoYp62pbtKd6/y5F+A==,type:str]
sops:
  age:
    - recipient: age136ladmslrftxhmkctamq7kpmpfdaqhz4m4pqqkz4vjdc5cpgeqmq27vk7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN3NXUnBKTUMxeHZFY0x6
        K2lhdUNlWDBPZ21sbnppcC9POEZZL1dFUjNZCmpQTG02UHc4dWw4b0FNY1Y3Rklt
        Y0xhaVpuM3RhTjVtZzZadU9TTW5uYk0KLS0tIGplSS84dHVRL3BNbjAzcVZpdWVX
        VFNNUUJXSkZqMU1YV0trWTFGT3ZoYkkKD+v6oWsSTo7Rj13TQTWVsOTesAnH4c/n
        tke/yM+OH6JkULPyvx0zonYQuucAG/Ygefg8VWEZWGdHjOGTgwYZpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-27T06:08:54Z"
  mac: ENC[AES256_GCM,data:JcL07MA625AOYTdkNkrC6T9ef32hbTW26aop7Q1+ZsFc4kBNH1/2F3IQsU8lVkwTN0Iw2hxObOmrYp3J7eVTS4A3kfkStFbW3wZ4RFgjTQXolwYNhWxplRfUwvn3YwG168ZdqOAHGVRNtgKxuo+8AhOPgUA3Zpn4Xd7zJ+ktyAM=,iv:LFmNpUC7FzZ4Rf8IQyfmOTL+CXY9SGO4I9Bg+Kqx424=,tag:A0U27V4nqC/iovThpX05Gw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
