# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:yEScooEom7+D2PEXSQ4YhjKaCxp1235DUBqG9F0/ILlxltXWhgNLbA==,iv:MnqPx7Vp6wlt3u1U60RI7Z1msTyEawmShkiJC9D2IKI=,tag:SXgDyZUr0zMQCM9GFkmprQ==,type:str]
sops:
  age:
    - recipient: age136ladmslrftxhmkctamq7kpmpfdaqhz4m4pqqkz4vjdc5cpgeqmq27vk7j
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTk1ZaG1Lc2FFZjBNK2lt
        SDIwWURjSHA2NUFMSUZ0bHBLT1poMFgzY3pJCktSM2poTnlTVFpJbmxVN0lrN0R5
        eUYrcVNtNm9VdUF4SG12V3pjTVpONncKLS0tIHRDdHRqMFU5QkVxaDNXYldyZFg5
        MUVGNHUrTnFhMXY4UU5LZ2JiVkpDcmsKJDdK7U7HtrL5aLZEj4wAWdopPlyZJTll
        Uq2ZgBNAfO4s+J6R9uXOlfe00gZNqvRhcB7vOfWo4MobRQMVl2jMuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T22:49:42Z"
  mac: ENC[AES256_GCM,data:c6OTmxb9Md6Fi7k/T7Vt9pGbGFIZyLGP1hI0rF9lxge7MmqOHT50WPqnC0vXVW8rDzPZzJ2hBcl6L4tBd6Od0plSpYpb+fmJBkpIKRyEHclfAwmQTbG6no4/Zrs/BLrUwRRJ6hlBqzr9iUoLirmh+B11zACc5fmDr9BZaY7dMrs=,iv:CkF+I97inGIsOMF8FUHCynh+YyGOwZwKEAY95kgjd8s=,tag:G//XrdlQ9OwORpIWt7TDEQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
